### ISSUE TITLE
Upcoming Workshops contains those from 2013

### ISSUE THREAD

**Issue by olexandr-konovalov** [LibraryCarpentry/librarycarpentry.github.io#1]
https://librarycarpentry.org/upcoming_workshops/ says "Upcoming Workshops" but lists all starting from 2013. Perhaps a title could be changed to e.g. "Our workshops". Alternatively, one could split past and future workshops in two pages, and also have a map of past/future workshops - it is very informative and very useful for making presentations.

Additionally, some links to past workshops are broken, or resolve to the same page, like e.g. "State Library of Western Australia, Perth" on 18-18 August 2017 (also the display of the date as "18-18 August" may be improved). 

Migrated from https://github.com/LibraryCarpentry/lc-second-website/issues/21

**Comment by libcce** [comment]
There are other feature requests to list:
- Automate the workshops page via an AMY feed
- Add a map to show workshops around the world

Data still needs to be corrected:
- Missing venue links (reach out to past instructors)
- Additional missing data like helpers, workshop numbers, etc

**Comment by maneesha** [comment]
@libcce  Are you building the workshop list manually?  We can have this come from AMY as it does for our other sites.  We are also considering ways we can list non-standard workshops in AMY and on the relevant websites and we should be able to automate that in the next few months.

**Comment by libcce** [comment]
@maneesha this was listed as an Asana project/task, to allow community members to submit workshops alongside workshops from AMY. LC workshops vary in what is taught and so many workshops would not be available in AMY (feeds) - they are seen as non standard. When there is a more inclusive approach for workshops it will be great to move this to an automated method. For now, the manual approach is not too much of a hassle.

**Comment by maneesha** [comment]
Following up on this issue (https://github.com/carpentries/carpentries.org/issues/334) we are making some changes to our workshop request forms and how we record workshops in AMY, so  we can revisit this and consider ways to include all workshops based on LC materials.

**Comment by maneesha** [comment]
Sorry for letting this issue linger!  We did make some changes last year that automate the creation of the upcoming and past workshop lists, so this should now be resolved.
