### ISSUE TITLE
Offset quote for Who is an instructor? section

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#10]
On the "About" page the "Who is an instructor?" section is in a stylized quote block.  Should this be formatted like all the other sections rather than this special style?

**Comment by libcce** [comment]
I'm partial to using the quote block. I'll wait to hear from others but I think we can keep this for now.

**Comment by maneesha** [comment]
OK.  @libcce  You can close this if you want then.

**Comment by katrinleinweber** [comment]
If it _is_ a quote, adding the source would make this more clear. Right now, it does look odd to me as well.

**Comment by libcce** [comment]
@katrinleinweber @maneesha the text is not a quote so I remove the quote https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/152aeb18c2bfdf88979362c0e613d1a48760a8bc
