### ISSUE TITLE
Update Library Carpentry FAIR Lesson Link

### ISSUE THREAD

**Issue by kariljordan** [LibraryCarpentry/librarycarpentry.github.io#105]
On the Library Carpentry **[lessons](https://librarycarpentry.org/lessons/)** page when I navigate to the Top 10 FAIR Data & Software Things lesson and click on **Site** it goes to this page: https://librarycarpentry.org/Top-10-FAIR/

The actual lesson is located here: https://librarycarpentry.org/lc-fair-research/

Can we change it so that the link to the site goes directly to the lesson? Also, in the [repository](https://github.com/librarycarpentry/Top-10-FAIR/) I think it would be helpful to have a link directly to the lesson.

**Comment by maneesha** [comment]
Fixed with #105 and issue raised in [this repo](https://github.com/LibraryCarpentry/Top-10-FAIR/issues/28) for reference.
