### ISSUE TITLE
Timeline - include incorporation as Carpentries lesson program

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#11]
For the timeline, under 2018 we should note that LC got incorporated as an official lesson program within The Carpentries.

**Comment by libcce** [comment]
Thanks. Just added this language https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/8c5dca7ae2c40019b44cd5a6b976e1c10c7cb902 .
