### ISSUE TITLE
Update the LICENSE in this repository

### ISSUE THREAD

**Issue by gvwilson** [LibraryCarpentry/librarycarpentry.github.io#11]
`LICENSE` still gives copyright to Barry Clark.

**Comment by jezcope** [comment]
Thanks @gvwilson, good spot (and thanks for your other work on this repo today!)

All: I propose either CC-BY or CC-BY-SA for the content of this website, with a slight preference for the latter. Views?

**Comment by gvwilson** [comment]
I'd be very grateful if LibraryCarpentry used CC-BY for everything, 
since both Software Carpentry and Data Carpentry have done so.  (No 
objections to -SA, but any license differences are likely to be stumbles 
down the road.)

**Comment by jezcope** [comment]
Seems reasonable to me!

**Comment by drjwbaker** [comment]
CC-BY http://data-lessons.github.io/library-data-intro/license/ so repeat everywhere (this is just legacy..)

**Comment by jezcope** [comment]
Resolved by #21
