### ISSUE TITLE
Let's consider removing 'past maintainers' on lessons

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/librarycarpentry.github.io#115]
For the sake of cleaning up the website & aligning with SWC & DC, let's remove the past maintains on https://librarycarpentry.org/lessons/. If we want to track past maintainers, we can on the lesson readme, but since authors (contributors) get added programmatically when we publish the lessons in Zenodo, I suggest we skip keeping track of past maintainers altogether.

**Comment by maneesha** [comment]
I think this is a good idea. It keeps us in line with the other lesson programs and is on a practical level, much easier to manage.

**Comment by ragamouf** [comment]
I agree also. the lesson readme is a good place to have a hall of fame for past maintainers.
