### ISSUE TITLE
Add Sara to list of Maintainers for FAIR lesson

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/librarycarpentry.github.io#118]
While reviewing #117 I noticed Sara El-Gebali needs to be added as (lead?) maintainer on the FAIR lesson.

**Comment by libcce** [comment]
Created https://github.com/LibraryCarpentry/librarycarpentry.github.io/pull/119 to add @selgebali 🎉

**Comment by tobyhodges** [comment]
Closed via #119
