### ISSUE TITLE
Library Carpentry Advisory Group Goals

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#128]
The [Library Carpentry Advisory Group page](https://librarycarpentry.org/advisory/) lists goals for 2019-2020.  
I'd recommend updating the dates and/or the content to reflect the current year.

**Comment by ragamouf** [comment]
We're in the process of reviewing these goals, and have set a deadline for 30 June to update with the new membership.

**Comment by maneesha** [comment]
Bumping this up. @ragamouf - have the 2019-2020 goals been updated? If the goals remain the same, could we remove the dates?

**Comment by annajiat** [comment]
Some goals will be continued, some new ones will be added, we are working on it. Thanks for the reminder.

**Comment by maneesha** [comment]
Thanks @annajiat 
Could we update the language:

> Advisory Group members will work on moving these goals forward from 2019-2021.

given we are more than half way through 2021? :-)

**Comment by maneesha** [comment]
We are now nearing late 2021. Could we update this page to reflect where things stand now (even if some work in in progress)?

**Comment by ragamouf** [comment]
@egrguric Here you go - with links! Adjust as you see fit :)

The 2021-2022 goals for the LCAG focus on governance and curriculum development. Achieving these goals will help the LCAG in succession planning, and develop expertise in recommending training resources to the Library Carpentry community. Use the issue links to follow progress.

1. Adopt Carpentries committee structure for the LCAG ([#34](https://github.com/LibraryCarpentry/governance/issues/34))
2. Align LC Curriculum Advisory Committee with Core Team efforts to refresh CACs across the Carpentries ([#38](https://github.com/LibraryCarpentry/governance/issues/38))
3. Identify hurdles to content contribution and develop rubric for vetting external content ([#36](https://github.com/LibraryCarpentry/governance/issues/36))
4. Highlight text analysis curricula from beyond the Carpentries 2022 ([#35](https://github.com/LibraryCarpentry/governance/issues/35))
