### ISSUE TITLE
Order of listing advisory group members

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#129]
Two recent PRs (#126  and #127) updated the [advisory group page](https://librarycarpentry.org/advisory/) with new members.  Profiles show up in the order they are listed in the [source data](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/main/_data/advisory.yml).  If the advisory council approves of the current order, we can close this issue.  Otherwise the data file should be re-organized based on the preferred sort order.  

We can also have this programmatically sort alphabetically.

**Comment by ragamouf** [comment]
Thanks Maneesha - I will ask the advisory group at our meeting this week.

**Comment by ragamouf** [comment]
We actually didn't get to discuss this issue at the meeting. I think programmatically sorting alphabetically on last name is the best solution because it is the simplest.
