### ISSUE TITLE
Should people contact LC director or just fill out form?

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#13]
The [workshops](https://librarycarpentry.org/workshops/) page says to fill out the request form *and* contact @libcce.  Do we need people to do both?

**Comment by libcce** [comment]
I'd like to move to using the request form but I'm listed in case they are thinking about custom/self organized workshops or have questions. If we find a way to record self organized workshops in AMY and present them via the feeds, then we can probably remove this and rely on the request form.

**Comment by maneesha** [comment]
@libcce 
 Could we have it say something like:

> To request a standard Library Carpentry workshop at your institution, visit the The Carpentries workshop request page. If you're interested other ways Library Carpentry lessons can be used at your site, please contact  Chris Erdmann, Library Carpentry Community and Development Director.

I just don't want people to have to fill in a form *and* send another email.

**Comment by libcce** [comment]
Thanks @maneesha! Update via https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/efb372d00108d72dbc92b785af345ae975873227
