### ISSUE TITLE
Order of Maintainers listed in lessons table 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#131]
This is a question that was inspired by this issue on the [Data Carpentry website repo](https://github.com/datacarpentry/datacarpentry.github.io/issues/566).

On the [LC lessons page](https://librarycarpentry.org/lessons/), is there any order to the way maintainer names are listed in each row?  I see some lessons (but not all) have a Lead Maintainer indicated by an asterisk.  

Should this person always be listed first, with all subsequent names in alphabetical order?
Should **_all_** names be listed in alphabetical order, with the Lead Maintainer still indicated with an asterisk?

**Comment by maneesha** [comment]
Bumping this up - how should we list maintainers?  Tagging @tobyhodges  as he was planning on bringing this up with the LC Advisory group.  Ideally I would like to see consistency across all lesson programs, but other lesson programs do not have lead maintainers.

**Comment by emcaulay** [comment]
I prefer alphabetical order regardless of whether a lead maintainer is noted or not. The asterisk can be appended to the lead maintainer's name in alpha order and serve the designation role.

**Comment by maneesha** [comment]
Fixed with #136
