### ISSUE TITLE
Advisory Group photos default to github

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/librarycarpentry.github.io#132]
In the last update, Eka Grguric's github profile photo is appearing on the LCAG page, and not the photo that she supplied  ( librarycarpentry.github.io/files/advisory/grguric.jpg). Does anyone know how to change this?

**Comment by libcce** [comment]
Hi @ragamouf, I updated https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/main/_data/advisory.yml and the img is there now https://librarycarpentry.org/advisory/ though it is rather egg shaped. @egrguric do you have a 300x300 pic handy? Then we can avoid the egg shape. The img will need to be here https://github.com/LibraryCarpentry/librarycarpentry.github.io/tree/main/files/advisory.

**Comment by egrguric** [comment]
Hi @libcce, I don't seem to have permission to push changes yet! Happy to make the change myself if I get permission.

**Comment by libcce** [comment]
@egrguric your pic should be fine now! @maneesha can possibly look into your privileges.

**Comment by ragamouf** [comment]
This looks good now - thanks @libcce!

**Comment by maneesha** [comment]
Thanks all - can we close this issue?
