### ISSUE TITLE
Updating country codes for LCAG

### ISSUE THREAD

**Issue by ragamouf** [LibraryCarpentry/librarycarpentry.github.io#133]
How do I update the country codes and check the preview? I changed an error in librarycarpentry.github.io/_data/advisory.yml (Eka is from CA not US) but it's appearing as a broken image. Do I need to wait, or are there other steps in the workflow for making minor updates to the LC website?

**Comment by ragamouf** [comment]
This is related to #134 Aussie updates - the website is showing that Mary Filsell and Sara King are from the US and not Aust.

**Comment by maneesha** [comment]
This looks ok to me now at https://librarycarpentry.org/advisory/
You will need to build the site locally to preview changes.  We haven't set up github based previews yet - we're working on it :-)

Can we close this?

**Comment by ragamouf** [comment]
Thanks @maneesha! Happy to close this - I don't know how to build the site locally, but that is something for another issue!

**Comment by maneesha** [comment]
Just FYI @ragamouf  Instructions to build the site locally can be found in this repo's readme.  Happy to answer any questions if the instructions are not clear.
