### ISSUE TITLE
Invalid link to submit a blog post

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#144]
Near the bottom of the [Get Involved page](https://librarycarpentry.org/get_involved/), there is a link to a google form to submit a blog post.  That form says it is no longer taking submissions.  

EDIT: This form is also linked to at the bottom of the [Stories from the Library Carpentry Community](https://librarycarpentry.org/our-stories/) page.

Tagging @kmomar  and @acrall on this as we consider how to manage our lesson program blogs in relation to the main Carpentries blog.

**Comment by maneesha** [comment]
@kmomar @acrall How would you like to handle this?

**Comment by kmomar** [comment]
@maneesha @acrall Since we are currently not accepting submissions to this blog and while we are considering the lesson program blogs in general, I would be in favor of removing this link.

**Comment by acrall** [comment]
Works for me too. Thanks @kmomar @maneesha

**Comment by maneesha** [comment]
Fixed with #150
