### ISSUE TITLE
update LC timeline

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#145]
I like the [Library Carpentry timeline](https://librarycarpentry.org/timeline/).  It stops at 2019.  What could we add to show what has happened in the past two years?

**Comment by libcce** [comment]
@arieldeardorff might be able to fill in info? Imagine we can add some more info from LCAG's mtg agendas/notes? CC @ragamouf

**Comment by jt14den** [comment]
@maneesha the link seems broken. Is the timeline somewhere else? I think this is year 10 of LC

**Comment by maneesha** [comment]
@jt14den I'm closing this as we have re-organized site content and as you noted, the link now goes directly to The Carpentries.
