### ISSUE TITLE
Suggestions and corrections (list)

### ISSUE THREAD

**Issue by ErinBecker** [LibraryCarpentry/librarycarpentry.github.io#15]
As part of my overall review of the page, here are some suggested edits and typo/link corrections:

# Homepage
- Homepage, who we are, instructors links to team page instead of instructors page - can use the text directly from The Carpentries homepage for this as it has links to the overall community page and several of the sub-communities. 
- List upcoming workshops on homepage? (can copy and modify code from carpentries homepage)
- Add link to subscribe to newsletter (can copy code from carpentries homepage)

# About
- Text under "who owns LC" can include more links embedded in relevant text. E.g. to SWC and DC, lessons
- "learnt" to "learned"??
- in section about Instructors, link to https://carpentries.org/community/#instructors

# Timeline
- reverse chronological order?

# Governance
- Might be good to add titles for each member. Is nice for people to be able to see the expertise behind the governance and might help potential members in making decision to join.

# Menu Bar
- Suggest making overall menu items the same as on Carpentries website and
- moving "Instructor Onboarding" to "Teach" menu
- moving "Our Lessons" to "Teach" menu
- adding links to "Become and Instructor" and "For Instructors" from "Teach" menu
- Add "Learn" top level menu item and include "Upcoming Workshops" and "Request a Workshop" as items

# Involved
- Lots of text, and people likely won't read all the way through. Add table of contents like https://carpentries.org/community/#instructors

# General
- governance group is in menu pull-downs in two places

**Comment by libcce** [comment]
Thanks @ErinBecker! I'm going to create a separate issue with some of your remaining issues:

Menu Bar
Suggest making overall menu items the same as on Carpentries website and
moving "Instructor Onboarding" to "Teach" menu
moving "Our Lessons" to "Teach" menu
adding links to "Become and Instructor" and "For Instructors" from "Teach" menu
Add "Learn" top level menu item and include "Upcoming Workshops" and "Request a Workshop" as items

Get Involved
Lots of text, and people likely won't read all the way through. Add table of contents like https://carpentries.org/community/#instructors

**Comment by libcce** [comment]
I'm reopening per @katrinleinweber.

**For Homepage:**

1. Update to Who We Are https://librarycarpentry.org/
2. Website traffic indicates that visitors are finding the upcoming workshops page (3rd visited page behind the lessons page and the homepage)
3. Add a link to Connect with Carpentries to https://librarycarpentry.org/contact/

Note: LC Maintainers are not listed on https://carpentries.org/maintainers/. Have created Asana task for @ErinBecker @libcce to address.

**Comment by libcce** [comment]
**For About:**

- Add links to CP, DC, and SWC.
- Correct 'learned' to 'learnt'
- Add 'For more about Carpentries instructors, see the Carpentries section on instructors.' w/ link to more info about instructors

**Comment by libcce** [comment]
**For Timeline:**

- Prefer starting w/ 2013 (@katrinleinweber what preference do you have?)

Note: Add 2019 bullet(s) -> Top 10 FAIR? Implementation completion? Maintainer discussions?

**Comment by libcce** [comment]
**For Governance:**

- Titles are not included on other Carpentries pages. Prefer to align w/ other Carpentry sites.

**Comment by libcce** [comment]
**For Menu Bar:**

- Since LC had fewer pages, decided to move lessons page, upcoming workshops page and others out of 'Teach' and 'Learn' to improve discovery/navigation for visitors. Usage indicates that visitors are finding 'upcoming workshops' more easily. It is the 3rd visited page behind the lessons page (2nd) and the homepage (1st).

**Comment by libcce** [comment]
**For Get Involved:**

- Add TOC and anchors https://librarycarpentry.org/get_involved/#Attend

**Comment by libcce** [comment]
**For General:**

- Prefer having Governance Group in two places but can move to one place (under People). @katrinleinweber ?

**Comment by katrinleinweber** [comment]
I have no feelings about the website's menu structure and am fine with whatever you feel is best, or have data about.

> Prefer starting w/ 2013 (@katrinleinweber what preference do you have?)

Fine with me, but I'm not sure what the alternative would be? Earlier, because other workshops had a librarian audience, or later because @drjwbaker produced the initial OERs?

I'd just suggest that for SEO reasons, we could add more links, see above ;-)

**Comment by drjwbaker** [comment]
I started on this in 2015 (first UK workshop, lessons published as Library Carpentry). 2013 refers to the Harvard workshop @libcce did, right?

**Comment by libcce** [comment]
2013 is when the first Carpentries workshops were taught to librarians at Harvard University, University of Toronto, Edmonton Public Library, University of Toronto, New York Public Library, Edmonton Public Library, and West Vancouver Memorial Library. Actually, most of these were taught by @cmacdonell. 

@katrinleinweber just so I understand correctly, are you saying we should link to the timeline from different places on the website and possibly add it to another menu item?

**Comment by libcce** [comment]
I'm closing this issue. I think most of the items have been spoken for. @katrinleinweber, please reopen the issue if you think there is anything I missed?
