### ISSUE TITLE
Upcoming Workshops out of date

### ISSUE THREAD

**Issue by cknuepfer** [LibraryCarpentry/librarycarpentry.github.io#168]
The page [Upcoming Workshops](https://librarycarpentry.org/upcoming_workshops/) does not show the upcoming workshops. There are several upcoming LC workshops listed on the [Carpentries Website](https://carpentries.org/) which are not shown here.

**Comment by maneesha** [comment]
Thanks @cknuepfer 
Can you email [workshops@carpentries.org](mailto:workshops@carpentries.org) with a list of the missing workshops so that we can look into this?

**Comment by cknuepfer** [comment]
I don't have such a list. But there are upcoming LC courses listed on the carpentries site (https://carpentries.org/upcoming_workshops/) which should also appear automatically on the LC site...

**Comment by maneesha** [comment]
Closing old issue - please re-open if there continue to be any errors.
