### ISSUE TITLE
Should LC have its own supporters page? 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#188]
### What is the problem?

The About menu links to a supporters page (https://librarycarpentry.org/supporters/).  Should LC have its own page of supporters, or should it re-direct to The Carpentries supporters page like the [DC website does for sponsors](https://carpentries.org/supporters/)?

**Comment by maneesha** [comment]
reminder @Talishask

**Comment by Talishask** [comment]
Thanks Maneesha, for now lets redirect as much as possible to The Carpentries site.

**Comment by maneesha** [comment]
Closed with #198
