### ISSUE TITLE
Consider removing LC events page

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#189]
### What is the problem?

There is an LC events page (https://librarycarpentry.org/events/) linked to from the "Connect" menu.  It is years out of date. Can we either update this page or remove this page entirely? @acrall

**Comment by maneesha** [comment]
If we remove the page, we can have the URL redirect to https://carpentries.org/community/#community-events

**Comment by maneesha** [comment]
@OscarSiba Let me know if you are ok with this.

**Comment by OscarSiba** [comment]
Yes, please re-direct @maneesha!
