### ISSUE TITLE
Consider re-directing LC Host workshop page

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#191]
### What is the problem?

Consider removing the section here (https://librarycarpentry.org/get_involved/#Host) and redirecting to go to The Carpentries Workshops page instead (https://carpentries.org/workshops/).

@sheraaronhurt  If you agree, I can make the change.

**Comment by maneesha** [comment]
@sheraaronhurt  I would also welcome your thoughts on other content on that page, specifically the section "Attend a workshop" and "Volunteer to help with a workshop" -- if the answer is not as simple as remove content and redirect, then please don't consider this a priority.  We will revisit when we start work on the new website again.

**Comment by sheraaronhurt** [comment]
I would recommend having everything redirected to one page that we will be able to keep accurate.

**Comment by maneesha** [comment]
closed with #197
