### ISSUE TITLE
Consider redirecting LC Instructor page

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#192]
### What is the problem?

Consider removing the section here on Apply to be an instructor (https://librarycarpentry.org/get_involved/#Apply) and redirecting to go to The Carpentries Become an Instructor page instead (https://carpentries.org/become-instructor/).

@karenword  If you agree, I can make the change.

**Comment by karenword** [comment]
lgtm!
