### ISSUE TITLE
Requesting Library Carpentry workshop

### ISSUE THREAD

**Issue by olexandr-konovalov** [LibraryCarpentry/librarycarpentry.github.io#2]
https://librarycarpentry.org/contact/ says "Want a Library Carpentry workshop at your institution? Request one." but the link navigates to requesting a Software Carpentry workshop (https://software-carpentry.org/workshops/request/). 

Going there, there is a button to request an SWC w/shop leading to https://amy.software-carpentry.org/forms/workshop/. For DC it says "If you would like a Data Carpentry workshop, please visit their web site", but if you go there, it then refers you back to the same https://amy.software-carpentry.org/forms/workshop/ form.

This all should be streamlined and untangled. For this LC site, one can link straight to https://amy.software-carpentry.org/forms/workshop/ instead of https://software-carpentry.org/workshops/request/.

Migrated from https://github.com/LibraryCarpentry/lc-second-website/issues/25

**Comment by libcce** [comment]
Request a workshop links have been updated:
https://librarycarpentry.org/workshops/
https://librarycarpentry.org/contact/

The links now point to a consolidated request form for The Carpentries:
https://amy.software-carpentry.org/forms/workshop/

**Comment by libcce** [comment]
Thanks @alex-konovalov ! Let me know if you spot anything else.
