### ISSUE TITLE
Delete gh-pages branch?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/librarycarpentry.github.io#20]
Since we are using `master` to generate the website, and [`gh-pages` is out-of-sync](https://github.com/LibraryCarpentry/librarycarpentry.github.io/compare/master...gh-pages?expand=1) by now, I plan to remove it. Objections?

**Comment by libcce** [comment]
I think this is a good idea. Just wondering how it will impact some of the links, like to lessons for example:

https://librarycarpentry.org/lessons/

We can always change the links though. Just nervous.

**Comment by katrinleinweber** [comment]
I'm quite sure that its latest version is on `master` ;-) Compare

https://github.com/LibraryCarpentry/librarycarpentry.github.io/blame/master/pages/lessons.html#L62

to

https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/gh-pages/pages/lessons.html

and to the live site. Belinda's last OpenRefine update is live, so it must have been generated from `master`.

**Comment by libcce** [comment]
Let's do it 😄 I'm nervous though. After setting up this site, I have memories of changes gone wrong. So I put my faith in you 😄

**Comment by katrinleinweber** [comment]
Thanks :-D I don't think it's technically possible to build a GitHub Page from different branches at once. The [pages docu states](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/): 

> […] repository named <username>.github.io or <orgname>.github.io […] are only published from the master branch.

Please have a look at [/settings](https://github.com/LibraryCarpentry/librarycarpentry.github.io/settings). If `gh-pages` isn't offer there as a page source, we are 100% good to delete it.

**Comment by katrinleinweber** [comment]
I'll do a final check of the differing commits and start a PR with all remaining commits that differ between `gh-pages` & `master`.

**Comment by katrinleinweber** [comment]
Hi @libcce! I can't view the settings, see above. Can you please check from which branch the site is generated?

**Comment by libcce** [comment]
Let's try to work this out via Zoom @katrinleinweber.
