### ISSUE TITLE
Add a "new lesson incubator"

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/librarycarpentry.github.io#22]
Prompted by @drjwbaker's comments in #20, I thought it might be good to have a separate "incubator" list of lessons that have been developed and/or taught under the LC banner but aren't yet mature enough to be officially adopted. I'm thinking that these lessons would be good to surface so that they can be taught a few times and given a chance to mature. I feel like this would be a good balance between avoiding good material getting lost and committing to maintaining and promoting every library-related lesson that comes along.

My current thoughts were either a separate section on the home page below the main lesson list, or a separate page entirely (but with a prominent link from the main lesson list).

Does this make sense? Any thoughts as to the best implementation?

**Comment by weaverbel** [comment]
@jezcope @drjwbaker Really keen to see this as it shows the dynamism of this space and opens up the opportunity for contributions from all over. I have pinged Tom and Brenda through the chatroom as to whether we can start by forking their existing work on web scraping . It also might lay the groundwork for things that could realistically be done if we run another two-day global sprint in June. I am not sure if MSL are running that again, but if not, we could still do our own sprint anyway - I am sure we would get a lot more particiaption given the vast interest we have had in the past year and the growth and spread of training and support for training. I think it would be good to link to all the the 'back end' repos from librarycarpentry.github.io so people can see what work is in progress and they can start to raise issues or fork and contribute.

**Comment by jezcope** [comment]
@weaverbel Great, thanks! So, potential lessons to include here so far:

- [Tidy data for librarians](https://github.com/jezcope/library-spreadsheets)
- [Library web scraping](https://github.com/timtomch/library-webscraping) (by @timtomch)

**Comment by drjwbaker** [comment]
My opinion: put it on the main page under the 'main' lessons; add the repos to 'data-lessons'; move SQL to incubator as - as far a I can see - it still needs some real playtesting to be a lesson proper.

Thanks for taking this forward @jezcope.

And agreed with @weaverbel: these are ideal candidates for the sprint (which we should do regardless of Mozilla - anyone know them enough to find out what is going on?)

**Comment by jezcope** [comment]
@weaverbel @drjwbaker Looks like this year's MSL global sprint is scheduled for 1/2 June: https://science.mozilla.org/programs/events/global-sprint-2017

**Comment by drjwbaker** [comment]
I look earlier this week but glad it is now there! Let's do it (I'll block out some time..)

**Comment by ccronje** [comment]
Wrt SQL discussion - the folks in Norway who contributed to Unix Shell also did this version of SQL https://scriptotek.github.io/library-sql/. There is this other version as well http://labs.timtom.ch/sql-novice-library/index.html

**Comment by drjwbaker** [comment]
Yeah.  Good point @ccronje. We have a few versions knocking around. I think we need to tidy this up during the sprint.

**Comment by weaverbel** [comment]
Great ! How shall we organise this year's sprint? Etherpad? Google form to sign people up? Zoom for daily catch ups? Happy to sort whatever works best to wrangle teams and do the blurb/paperwork for MSL so we get our project listed early on. I'll also do a blog post for SWC we can all tweet and we should post it on librarycarpentry.github.io as well. I will be in transit most of May (US, Scotland, France) so I would like to get the organising work done before I fly off to Portland on 30 April.

**Comment by timtomch** [comment]
Hi there! Happy to contribute the webscraping lesson. I have now taught it three times, and finally last week at the code4lib conference in LA I was finally happy with it. The text still needs some smoothing over (particularly the XPath section), timing needs to be reworked and the episodes that I have now moved into the "extra" folder as the lesson would be too long otherwise still remain to be rewritten, but I'm finally no longer ashamed of the lesson. How should I proceed, do you want to fork my repo or should I transfer the lesson repo to LC?

**Comment by drjwbaker** [comment]
Right. I've opened an issue at https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/23 @weaverbel are you happy to do this initial MSL registration?

**Comment by weaverbel** [comment]
Hi @timtomch I think you should keep your own copy and we can fork a version of it into LC as the lessons might end up diverging. What do others think?

**Comment by amyehodge** [comment]
I also have a modified version of the SQL workshop that I teach from regularly at https://github.com/amyehodge/amyehodge.github.io/tree/master/Beginning_SQL. I think the biggest modification is that I have attempted to get the queries to build up into a big query over time instead of starting over a lot. Hope that makes sense.

**Comment by drjwbaker** [comment]
@amyehodge Thanks so much for sharing. This is super helpful.

Who is leading on maintaining/reworking the SQL lesson. @c-martinez?

**Comment by c-martinez** [comment]
During the sprint? I don't think anybody has volunteered for it, explicitly.

**Comment by drjwbaker** [comment]
@c-martinez Both: it isn't clear to me who is maintaining or if anyone is willing to lead on this for the sprint.

**Comment by c-martinez** [comment]
@drjwbaker -- @mkuzak and me are maintainers of SQL lesson, but I we are not working on the lesson during the sprint. I'll keep an eye out for PR's but will mainly concentrate on Python new lesson.

**Comment by mkuzak** [comment]
my primary target for the sprint was OpenRefine lesson, but may also work on SQL if time allows

**Comment by drjwbaker** [comment]
Okay. Totally understand. As maintainers perhaps you could coordinate a few simple tasks during the sprint:

1) moving the lesson to incubator ( @jezcope: are you coordinating space/language around this new designation?)
2) seeing if there are people who want to work on the lesson
3) checking back in on their work post-sprint, especially if a potential new maintainer or two emerge

Is that something you can look at?

**Comment by drjwbaker** [comment]
Close as superseded by https://github.com/data-lessons/librarycarpentry/issues/22
