### ISSUE TITLE
Mozilla Global Sprint 2017, 1-2 June 2017

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/librarycarpentry.github.io#23]
**SUPERCEDED AT https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/23#issuecomment-290058114**

Issue to setup inital organisation of Library Carpentry activities at Mozilla Global Sprint 2017 https://science.mozilla.org/programs/events/global-sprint-2017

Initial proposed work:

- work on incubator lessons: https://github.com/jezcope/library-spreadsheets; https://github.com/timtomch/library-webscraping
- bring together various SQL lesson threads https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/22#issuecomment-285663565
- refresh/revise http://librarycarpentry.github.io/
- develop a proper workflow for monitoring upcoming workshops and publishing our (impressive!) list of events in a public place
- fix the logo https://github.com/data-lessons/librarycarpentry/issues/15#issuecomment-267349540

Etherpad to be used for coordinating.

James and Belinda to coordinate.

**Comment by weaverbel** [comment]
Hi @drjwbaker I have created the etherpad and tweeted it. If someone could re-tweet from LibCarpentry that would be good too. I'll talk to MSL - project calls are not open yet but we have everything we need to register  since we created all the right stuff last time. Happy to sort that. We should try to get this message out to archivists (see the chatroom) http://pad.software-carpentry.org/lc2017

**Comment by jezcope** [comment]
More possible work to be done from various discussions:

- Revamp the Python lesson to be more realistic for the audience (maybe split into multiple lessons?)
- Free workshop data from the shackles of Google Sheets
  - Rendered on the website
  - Downloadable in machine-readable form e.g. JSON
- Develop material for archivists (and improve comms to non-librarian information professionals)

**Comment by weaverbel** [comment]
@drjwbaker @jezcope I think we need to start drafting a plan of work for the sprint - tell people exactly what we want to get done, e.g. bug fixes like typos, errors; melding all the SQL lessons into one; badging up Tom's web scraping lesson for LC; maybe also badging Brenda's Beautiful Soup Python web scraping lesson as an alternative web scraping lesson; @ostephens 's XSLT lesson dev if that is happening; and also fixing the Python lesson - we will have more intel about that once we have had our meetup. Shall I start a Google Doc for the sprint - we could use markdown formatting so we can post it on GitHub nearer the time. Or shall I just start the document on GitHub? If so, which will be the repo people go to to find out about the sprint work? Is it github.com/LibraryCarpentry? Happy to get going on that - I could paste these ideas in for a start and then we can start to flesh out proper instructions - i.e. forking, keeping PRs small (one or two changes at a time), raising issues, using the chatroom.

**Comment by ostephens** [comment]
I'm not sure I intended to put my hand up for XSLT lesson dev!

I'd like to see the 'Archive Carpentry' idea on the list and I'd be interested in working on either that, or on getting a web scraping lesson done.

I think getting a public document for the sprint is a good idea. Google Docs works for me, and might let us source ideas from a wider range of people than doing it straight into GitHub

**Comment by ostephens** [comment]
Digging out some previous discussion about XSLT/XPath from the Gitter chat, I think we boiled down to two use cases - quote myself:

> @drjwbaker So I think from @timtomch we have the web scraping/HTML parsing use case
> @drjwbaker and from Nora we have the TEI processing /Digital Humanities use case

Potentially I'd add to these:

- Using XSLT/XPath with EAD
- Using XSLT/XPath with MODS

**Comment by weaverbel** [comment]
Sorry @ostephens I didn't mean to dob you in - I just vaguely recalled XSLT being raised. I think we should concentrate on the other stuff but didn't want to discourage people from cracking on with new stuff if that is what floats their boat. Happy to go with a Google Doc - we can lodge it in GitHub once the outline has been firmed up.

**Comment by drjwbaker** [comment]
Thus far we have:

**lessons**
- work on updating and badging incubator lessons: https://github.com/jezcope/library-spreadsheets; https://github.com/timtomch/library-webscraping
- bring together various SQL lesson threads https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/22#issuecomment-285663565
- Archive Carpentry [is this an archives focused version of an existing lesson?]
- SQL

*admin**
- develop a proper workflow for monitoring upcoming workshops and publishing our (impressive!) list of events in a public place by freeing workshop data from the shackles of Google Sheets: rendered on the website; downloadable in machine-readable form e.g. JSON
- fix the logo https://github.com/data-lessons/librarycarpentry/issues/15#issuecomment-267349540
- refresh/revise http://librarycarpentry.github.io/

**Comment by timtomch** [comment]
I'm unfortunately not able to participate in the sprint but I will endeavour to cleanup the webscraping lesson before that. Also the XPath section of that lesson was mainly written by @kimpham54 who might be interested in doing more XPath/XSLT stuff.

**Comment by jezcope** [comment]
@weaverbel :+1: to Google Doc, unless you want to try one of the options listed here (shameless plug): [Tools for collaborative markdown editing](https://erambler.co.uk/blog/collaborative-markdown-editing/)

**Comment by ccronje** [comment]
If you want to get from Google Docs to markdown post-sprint, the [Export as Markdown](https://chrome.google.com/webstore/detail/export-as-markdown/hbojhdcnbcondcdfpfocpkjkfkbnbdad?hl=en-US) add-on is pretty neat (nice way of liberating Word docs too via Google Docs upload).

**Comment by weaverbel** [comment]
@ostephens @drjwbaker  I've just been invited to do a one-day LC workshop at an archivists' conference in Australia in September. All the more reason to get some archivist input to the sprint to help inform that workshop. I was thinking of creating a short Google form to ask archivists what they would like to see in our lessons to make them more relevant to their needs. We could all tweet that form link and maybe get some input that might translate into workable sprint ideas (and maybe attract some keen people to be part of the sprint). Thoughts?

**Comment by timtomch** [comment]
@weaverbel that echoes some of the comments heard this spring at code4lib in LA. I have a couple of archivists friends that I know would be eager to contribute their thoughts. Google form is a good idea.

**Comment by weaverbel** [comment]
Thanks @timtomch I might draft a form and post it to the chat room for comment before I make it live.

**Comment by weaverbel** [comment]
OK, @ostephens @timtomch @drjwbaker @jezcope @ccronje I have drafted a form for archivists - big enthusiasm here to get this out to archivists - what do people think of the questions? Happy to tweak. https://docs.google.com/forms/d/e/1FAIpQLSdc9RHNmgffnt9UtLfgIhS_MGUzh0wh-HQNX24wBz5c4mcf1g/viewform

**Comment by drjwbaker** [comment]
I like it. I also approve of the use of 'town' rather than 'city' :)

**Comment by ostephens** [comment]
+1

**Comment by weaverbel** [comment]
Ok @ostephens - done

**Comment by ccronje** [comment]
I'd like to work on OpenRefine for the Sprint. I could start with [the issues](https://github.com/data-lessons/library-openrefine/issues) on making episodes more granular. There is a bigger discussion to be had though, about adding new examples and the length of workshop. OpenRefine is a good candidate for an Intro/Advanced workshop split. Advanced could explore more GREL and API examples (parsing JSON etc). @ostephens also mentioned XPath wrt Jython on GItter. We could shift the current advanced episode over and expand with examples. Too much to resolve in a Sprint? ;-) Happy to chip away on the smaller things.

**Comment by drjwbaker** [comment]
@ccronje Given how much chatter we've had around the Refine lesson, it strikes me that it would be sensible to use the sprint to resolve (or at set out a plan for resolving) these nagging issues. I'll leave you as OR maintainers to decide how/what.

**Comment by weaverbel** [comment]
Should we try to adapt this Contributor guide from Data Carpentry to describe the work for our sprint ?
 https://github.com/datacarpentry/lesson-release/blob/master/how-to-contribute.md

**Comment by ccronje** [comment]
@weaverbel did you see this by @jt14den & colleagues? http://www.tim-dennis.com/swc/2016/07/25/contributing-carpentries.html

**Comment by weaverbel** [comment]
No @ccronje I hadn't seen that but it looks good ! We probably need a sprint to work out how to write the CONTRIBUTING.md for the sprint ;-)
