### ISSUE TITLE
Archive Carpentry?

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/librarycarpentry.github.io#25]
*Opening an issue to help organise our thoughts*

## Background

- Library Carpentry has seen interest from archivists in our lesson materials and workshops.
- We don't want to confuse matters or spread ourselves too thinly by trying to start Archive Carpentry alongside Library Carpentry (especially in the context of the proposed Software/Data Carpentry merger https://software-carpentry.org/blog/2017/02/merger-discussion.html).
- Instead, our plan right now is to "try to get some archivists to join the [global sprint](https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/23) [in June] and repurpose some lessons for their own use”.
- To feed into that, @weaverbel put together a survey on ['Archivists' Wish List'](https://docs.google.com/forms/d/e/1FAIpQLSdc9RHNmgffnt9UtLfgIhS_MGUzh0wh-HQNX24wBz5c4mcf1g/viewform) for Library Carpentry. We got a good response and the results need to be processed/considered in advance of the sprint.

**Comment by drjwbaker** [comment]
**API lesson** Potential API lesson. Ideally json based and read/write. Ideas:

- http://www.meanboyfriend.com/overdue_ideas/2016/06/introduction-to-apis-using-iiif/
- https://github.com/hughrun/rijks-teen-press
- https://hughrun.github.io/recipe_trove/
- https://gist.github.com/VladimirAlexiev/e51e256be18870ac5033901197ee8277
- http://www.nationalarchives.gov.uk/help/discovery-for-developers-about-the-application-programming-interface-api/

**Comment by ostephens** [comment]
DPLA API + Ideas on using it https://dp.la/info/developers/ideas-and-projects/current-ideas/

**Comment by ablwr** [comment]
+1 to all of these things and the project! Thanks everybody!

This may be too closely related to the existing introduction to shell, but I think that file format transformation specifically may be relevant to archivists (both how to do this, usually via CLI, but also why, an understanding of preservation-grade file formats and access-grade formats, basics of compression, etc).
A resource is here (particularly the first section): https://datapraxis.github.io/sourcecaster/
And for a/v-specific transformations: https://amiaopensource.github.io/ffmprovisr/ 

I think the previous thread mentioned XSLT, which may be useful due to the wide use of EAD, an XML format, and the need to clean up data styled in that way!
I taught some basics last year, there are some links and quick-tips in this directory: https://github.com/ablwr/xslt_miap_2016

**Comment by drjwbaker** [comment]
@ablwr Thanks for your input! Glad to see you found Sourcecaster: I worked on that with @thomasgpadilla.

On XSLT, this has bubbled up a few times - for example we had this https://github.com/data-lessons/librarycarpentry/issues/14 discussion last year. I don't know enough to comment really but it feels like we've always decided not to proceed. What I don't want us to do is to duplicate good work elsewhere - for example at Programming Historian by @mhbeals http://programminghistorian.org/lessons/transforming-xml-with-xsl - if something like that will more or less fit what librarians and archivists need from an intro to XSLT. If, however, the case can be made that they need something else and that we have the expertise and will to work up a lesson, then I can get behind it.

**Comment by ablwr** [comment]
It was easy to find Sourcecaster because I made ffmprovisr, from which the codebase is forked. 😅

**Comment by drjwbaker** [comment]
Huh. Awesome!

**Comment by drjwbaker** [comment]
[From Jenny Bunn on the Gitter](https://gitter.im/weaverbel/LibraryCarpentry?at=58ef45b9f22385553d389255):

> Thanks for the welcome and sorry for the radio silence - been on holiday for a few days. In response to all the questions/comments. Archives Hub are much loved and are as technical as it gets in archives in the UK. I would be loathe to speak on their behalf as Jane Stevenson (https://www.jisc.ac.uk/staff/jane-stevenson) is more than capable of speaking for herself, but for an idea of some of the things they have been involved in see http://data.archiveshub.ac.uk/about.html. I guess their engagement in this area is explained in part by their status as an aggregator - they have no collections of their own, just other people's data so their focus can be solely on that data, how it is stored, imported, exported, shared etc. I'd be happy to help out by looking at the feedback on Archives Carpentry, but in answer to the initial questions. The technical skill/context that is most relevant to archives is probably around data cleansing - this in particular since dealing with born digital records became more common place. At the moment smaller archives favour tools like DROID (developed by The National Archives) but they tend to take the data from that and put it into Excel - indeed many archivists I have spoken to would just like better Excel skills. There is also recognition though that this sort of hand cranked process is not going to work at scale. So the main context is born digital records and digital preservation mainly and the skills are around just dealing with data. There is another side though that sees archives as interested in how they can use technology for recordkeeping aims, e.g. the use of block chain technology in service of the archival aim of authenticity and linked data/semantic technologies in service of encoding/preserving meaning. That is a bit more out there at the moment though. Anyway, hope that helps and if you send me the link, I will look at the feedback.

**Comment by drjwbaker** [comment]
Close as discussion on main LC repo
