### ISSUE TITLE
About page variable expansion broken

### ISSUE THREAD

**Issue by ilessing** [LibraryCarpentry/librarycarpentry.github.io#29]
When you do a Google search for "Library Carpentry" there is some odd double curly braced 'title' word showing for the About page
<img width="880" alt="screen-shot-2019-02-13-library-carpentry-google-search" src="https://user-images.githubusercontent.com/275899/52890944-65f71080-313c-11e9-8d00-9cc20f0440d7.png">
You won't see this if you look at the [About page](https://librarycarpentry.org/about/) unless you're using a screen reader.
I suspect this is happening because you don't get variable expansion within .yml files with Jekyll.
see file [_data/language.yml](https://github.com/LibraryCarpentry/librarycarpentry.github.io/blob/master/_data/language.yml) line 6
Can the WAVE accessibility issue be addressed by some other means? @libcce

**Comment by jscaffrey** [comment]
Thank you for identifying and reporting the issue. I just submitted PR #30 which should resolve this.

**Comment by libcce** [comment]
Thanks @ilessing @jscaffrey @katrinleinweber 😃 I've merged @jscaffrey's PR https://github.com/LibraryCarpentry/librarycarpentry.github.io/pull/30.
