### ISSUE TITLE
Icon for Topicbox not displaying in footer

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/librarycarpentry.github.io#3]
Icon for Topicbox LC discussion list not displaying correctly in website footer (last icon displays as a question mark).

**Comment by katrinleinweber** [comment]
Not sure why this didn't work, I'm sorry! I was [pretty sure](https://fontawesome.com/v4.7.0/icon/envelope) it would :-/

**Comment by libcce** [comment]
@weaverbel do you know how we can add a 'mail' icon for Topicbox to the footer?

**Comment by libcce** [comment]
@katrinleinweber I have the Gitter icon pointing to the connect/contact us page now. It's hacky but it works.
