### ISSUE TITLE
Library carpentry Lessons drop down list on website problem

### ISSUE THREAD

**Issue by U2NG** [LibraryCarpentry/librarycarpentry.github.io#35]
The lesson dropdown list on the library carpentry website is only showing the Top 10 Fair Data and Software link.  The other lessons are not displayed.

**Comment by ostephens** [comment]
The Top 10 Fair Data & S/W link was added in this commit https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/0912ced2c5483e0d3c03a3c0894d4ef2284633ab

Prior to that there was no drop-down on Lessons navigation in the menu bar - it just went direct to the lessons page.

At the moment the Top 10 Fair Data & S/W doesn't seem to be listed on the lessons page? Maybe the resolution would be to add it there and revert the other change?

**Comment by libcce** [comment]
@U2NG @ostephens I didn't know exactly what to do with listing the Top 10 FAIR Data & Software lessons. It's new and didn't believe it should be listed on the lessons page until we test it out further. The "Our Lessons" top-level nav link still directs you to the lessons page. @jt14den @ccronje @erikamias @laufers @katrinleinweber do you have follow up advice?

**Comment by ostephens** [comment]
@libcce a suggestion - could they go under the Experimental/Conceptual Curriculum section of the lessons page?

In terms of the Lessons dropdown - if we want navigation at this level I think it should be consistent - calling out a single lesson / set of lessons here and not the others feels counter-intuitive. So if we want a dropdown here it could go to the sections of the Lesson page (Core / Extended / Experimental)?

Happy with alternative approaches though

**Comment by libcce** [comment]
@ostephens That works for me, to list it under the Experimental/Conceptual Curriculum section. I'll pause just in case someone else wants to comment but this seems like a good approach, to list it there.

**Comment by U2NG** [comment]
I agree, listing under the Experimental/Conceptual section would be a good place for the Top 10 FAIR Data & Software lesson.

**Comment by katrinleinweber** [comment]
I don't have an opinion about this.

**Comment by libcce** [comment]
@U2NG @ostephens Let me know what you think of how the website is organized now: https://librarycarpentry.org/

**Comment by katrinleinweber** [comment]
This seems fixed to me by d83655ff348eb9a5c354781053277d7253e17169 & 1b5369e83f00b3f110994ce0aae2aa9a6725f1bc.

**Comment by libcce** [comment]
I think so too but I'll wait a couple days to hear from @U2NG. Thanks for pinging us again on this @katrinleinweber !

**Comment by libcce** [comment]
Looks like this has been solved. Closing. Thanks, everyone!
