### ISSUE TITLE
Submit to libraryskills.io?

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/librarycarpentry.github.io#40]
They have several collections of skills, among them "Code Club facilitator". This, or others might be a good place to submit our Core Curriculum to, or the stable lessons individually.

What do you think?

**Comment by libcce** [comment]
Great suggestion! I just submitted LC to the site. We encompass so many categories I decided to use "Other". I pointed to https://librarycarpentry.org/lessons/ and used "Software and data skills for people working in library- and information-related roles" for the description. How did you come across this site? Looks great!

**Comment by katrinleinweber** [comment]
Cool, thanks :+1: Lets re-open this, if we need to discuss any kind of re-submission or similar should they not add us directly.
