### ISSUE TITLE
Add web analytics to website

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/librarycarpentry.github.io#5]
I'm assuming Google Analytics but there are other options. Any suggestions/preferences?

**Comment by drjwbaker** [comment]
No idea. Is it evil despite their don't be evil stance?

**Comment by jezcope** [comment]
I don't really have any problem with Google Analytics, I just wanted to give an opportunity for anyone who might have strongest preferences a chance to express them! I've used Woopra in the past and their realtime analytics are much better if that's likely to be of interest (e.g. during presentations about LC and/or workshops).

The one thing I'd quite like which isn't easily doable with GA is to make the data public, both for openness and transparency, and because it might be a useful dataset for lessons. I'm not sure of a platform that allow that, but I'm open to suggestions.

In the meantime, unless there are strong objections I suggest we stick GA in there to at least start getting some data.

**Comment by jezcope** [comment]
I'll close this as it's handled by #6 — if we want to change analytics platforms we can always open a new issue.

For reference, there's a [public spreadsheet with the last 28 days-worth of analytics data on it](https://docs.google.com/spreadsheets/d/1gQG2A9zsOwrgg2Mp4uc4UcGK8OrVGpGfVjud_6vS_eM/edit?usp=sharing)
