### ISSUE TITLE
Is "Connect" the right heading to use in the site navigation?

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/librarycarpentry.github.io#5]
Received comment that it was difficult to find "Our Events" which is listed under "Connect".

**Comment by katrinleinweber** [comment]
Was it a singular opinion, or several voices? I suggest to keep a tally of :+1: and only act once a few have accumulated.

**Comment by libcce** [comment]
It was singular. I was just logging it here in case there are more voices 😃

**Comment by libcce** [comment]
I haven't heard of others having issues. Closing.
