### ISSUE TITLE
Incomplete paragraph on "Our Workshops" page

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/librarycarpentry.github.io#59]
The third paragraph on [Our Workshops](https://librarycarpentry.org/workshops/) ends mid-sentence. I'm happy to submit a pull request fixing this but I'm not sure what that sentence is supposed to say! The paragraph in question is (emphasis mine):

> An official Library Carpentry workshop must include three to four of our core lessons. All workshops that are reported to Library Carpentry are listed in the ‘Upcoming Workshops’ section of this site and range from 1-day to multi-day. See What constitutes a Library Carpentry workshop? and Seventy-One Workshops… and Counting for further information. All participants must be prepared to observe The Carpentries Code of Conduct in workshops. Library Carpentry lesson materials are freely available under a permissive open license and available for the wider community to use for Library Carpentry-based workshops. **Library Carpentry workshops that are report**

**Comment by libcce** [comment]
Hi @jezcope that section and another section which also may be incomplete were added through commits by @maneesha (https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/a36f6d4d372df246308e1e1696812acc0646092e#diff-e68b943d073a94fa08120e46fadabded and https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/a6077b5525f05dfde5496f3b641a6ec2d060e4e9#diff-e68b943d073a94fa08120e46fadabded). Maneesha can you help here?

**Comment by maneesha** [comment]
Looking further back at the "blame" history it looks like that incomplete sentence was there before the commits I made.  I'm not sure what that sentence was supposed to say;  if Chris is not sure either I'd recommend removing it.

**Comment by libcce** [comment]
I removed the sentence and also fixed the Regional Coordinators section https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/97b4b331d33290fb0e2c30b017da1a32bcae1619 Thanks @jezcope @maneesha!
