### ISSUE TITLE
RSS and Atom displaying correctly?

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/librarycarpentry.github.io#6]
Hi @cmacdonell are the RSS and Atom feeds displaying correctly? I switched the URLs over to librarycarpentry.org. Atom is working for me in Chrome. I receive a blank page in Chrome when I visit the RSS link but when you view the underlying code, you can see the RSS. Here are the two links https://librarycarpentry.org/atom.xml and https://librarycarpentry.org/feed.xml. Others are welcome to respond if they are having issues and/or provide a fix 😃

**Comment by cmacdonell** [comment]
Hi @libcce, I haven't had a chance to look yet. Interestingly both Atom and RSS works for me in Chrome.  Neither seem to work in Firefox, I get ugly HTML in both cases.

**Comment by jezcope** [comment]
@libcce They both display the latest articles for me (Firefox). Have you got a cached version of something maybe?

**Comment by libcce** [comment]
That's good to hear @jezcope! @cmacdonell have you tried clearing your cache? It works for me in Firefox as well. Seems like Chrome is fine as well. @jezcope can you check Chrome as well to see if it is working on your end?

**Comment by cmacdonell** [comment]
I've tried Firefox on another computer and it works fine. I didn't investigate whether it was the cache or not, but I'd suggest we leave this for now.

**Comment by katrinleinweber** [comment]
In my Firefox with [Brief](https://addons.mozilla.org/de/firefox/addon/brief/), the atom feed works fine :-) RSS is not displayed for some reason, but Firefox' dynamic bookmark loads it just fine.

**Comment by libcce** [comment]
I believe this is fixed. @cmacdonell do you agree?

**Comment by libcce** [comment]
Pinging @cmacdonell again. I believe this issue is fixed?

**Comment by cmacdonell** [comment]
Sorry for the delay. I think it is fixed, yes. Works on Chrome and Firefox.

**Comment by libcce** [comment]
Thanks @cmacdonell! Finally closing this issue (I thought I had already)!
