### ISSUE TITLE
Should SQL move to top of table?

### ISSUE THREAD

**Issue by ccronje** [LibraryCarpentry/librarycarpentry.github.io#71]
Now that SQL has moved to stable should it move up in the Extended Curriculum table? https://librarycarpentry.org/lessons/

**Comment by libcce** [comment]
Seems like a good idea 👍

**Comment by maneesha** [comment]
Thanks @libcce and @ccronje 
Would either of you be interested in putting in a PR?

**Comment by libcce** [comment]
@maneesha thanks to @ccronje this issue is done. The change is already live. We can close this.
