### ISSUE TITLE
The Carpentries Tagathon - Suggest Relevant Tags for Blog Posts

### ISSUE THREAD

**Issue by serahkiburu** [LibraryCarpentry/librarycarpentry.github.io#73]
October 28  to November 1 2019 is The Carpentries Tagathon week. This means we will be working to add relevant tags to as many posts as possible on the [Data Carpentry](https://datacarpentry.org/blog), [Library Carpentry](https://librarycarpentry.org/blog) and [Software Carpentry](https://software-carpentry.org/blog) blogs. More information about this initiative is available [in this blog post](https://carpentries.org/blog/2019/10/carpentries-tagathon/).

You can contribute to this initiative by reading the posts on any of the three blogs, and suggesting between one and three tags that should be added to the posts. 

The Carpentries Handbook has [a detailed guide on adding tags to blog posts](https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html) published across all  our blogs. 

All Pull Requests associated with the Tagathon and touching on any of the 45 Library Carpentry blog posts will reference this issue, so you can keep track of them below. 

---

Interested in suggesting tags for posts in Data Carpentry and Software Carpentry blogs too? See what others have worked on under the
* [Carpentries Tagathon issue](https://github.com/datacarpentry/datacarpentry.github.io/issues/499) on the Data Carpentry repository
* [Carpentries Tagathon issue](https://github.com/swcarpentry/website/issues/1086) on the Software Carpentry repository
and start contributing.

**Comment by ghost** [comment]
If we want to suggest tags for multiple posts, should we make a pull request for each blog post? Or is it ok to include changes to multiple blog posts in a single pull request?

**Comment by serahkiburu** [comment]
hey @burrowsdt, either option works well.

**Comment by ceesu** [comment]
I noticed that some of the tags on https://librarycarpentry.org/posts-by-tags have quotation marks around them, and some do not (e.g. "Community" and Community). Was this intentional?

**Comment by serahkiburu** [comment]
Hi @ceesu, those need fixing. A PR with fixes would be highly appreciated

**Comment by ceesu** [comment]
@serahrono Okay, I'll try and see if I can figure it out!

**Comment by ceesu** [comment]
I think I have fixed the tags with typographic quotation marks, I've included this in PR #81.

**Comment by kariljordan** [comment]
Hi! I was creating an issue in this repo and saw that this is open. Can we close this now?

**Comment by maneesha** [comment]
@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open?
