### ISSUE TITLE
require certified Carpentries instructors

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.github.io#9]
The "About" page says:

>To maintain the quality of Library Carpentry workshops, it is highly recommended that a Carpentries-certified instructor be present at each workshop.

Now that LC is officially a lesson progra, we should be mandating that at least one Carpentries certified instructor is teaching, correct?

**Comment by libcce** [comment]
Yes, this is fixed with https://github.com/LibraryCarpentry/librarycarpentry.github.io/commit/a11aad7d98abf4bcc4cf266796735edd7a219d18. Thanks again!
